/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package apresentacao;

/**
 *
 * @author nickb
 */
public class frmCalculadora extends javax.swing.JDialog {

    /**
     * Creates new form frmCalculadora
     */
    public frmCalculadora(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    
    double num1;
    double num2;
    double resp;
    String resposta;
    String op;
    int multiplaConta = 0;
    
    public static String[] vetor = new String[5];
    
    public void registrarHistorico()
    {
        if(vetor[0] == null)
        {
            vetor[0] = num1 + " " + op + " " + num2 + " = " + resposta;
        }
        else
        {
            for(int i = 4 ; i > 0 ; i--)
            {
                vetor[i] = vetor[i-1];
            }
            vetor[0] = num1 + " " + op + " " + num2 + " = " + resposta;
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPONTO = new javax.swing.JButton();
        btnZERO = new javax.swing.JButton();
        btnRESP = new javax.swing.JButton();
        btnSOM = new javax.swing.JButton();
        btnTRES = new javax.swing.JButton();
        btnDOIS = new javax.swing.JButton();
        btnUM = new javax.swing.JButton();
        btnSEIS = new javax.swing.JButton();
        btnSUB = new javax.swing.JButton();
        btnCINCO = new javax.swing.JButton();
        btnQUATRO = new javax.swing.JButton();
        btnOITO = new javax.swing.JButton();
        btnMUL = new javax.swing.JButton();
        btnSETE = new javax.swing.JButton();
        btnNOVE = new javax.swing.JButton();
        btnAPAGAR = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnDIV = new javax.swing.JButton();
        txfCAMPO = new javax.swing.JTextField();
        btnEDIT = new javax.swing.JButton();
        btnHISTORICO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CALCULADORA");
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btnPONTO.setBackground(new java.awt.Color(45, 45, 45));
        btnPONTO.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnPONTO.setForeground(new java.awt.Color(255, 255, 255));
        btnPONTO.setText(".");
        btnPONTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPONTOActionPerformed(evt);
            }
        });

        btnZERO.setBackground(new java.awt.Color(63, 63, 63));
        btnZERO.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnZERO.setForeground(new java.awt.Color(255, 255, 255));
        btnZERO.setText("0");
        btnZERO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnZERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZEROActionPerformed(evt);
            }
        });

        btnRESP.setBackground(new java.awt.Color(51, 153, 255));
        btnRESP.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnRESP.setForeground(new java.awt.Color(255, 255, 255));
        btnRESP.setText("=");
        btnRESP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRESPActionPerformed(evt);
            }
        });

        btnSOM.setBackground(new java.awt.Color(255, 102, 0));
        btnSOM.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnSOM.setForeground(new java.awt.Color(255, 255, 255));
        btnSOM.setText("+");
        btnSOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSOMActionPerformed(evt);
            }
        });

        btnTRES.setBackground(new java.awt.Color(63, 63, 63));
        btnTRES.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnTRES.setForeground(new java.awt.Color(255, 255, 255));
        btnTRES.setText("3");
        btnTRES.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTRES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTRESActionPerformed(evt);
            }
        });

        btnDOIS.setBackground(new java.awt.Color(63, 63, 63));
        btnDOIS.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnDOIS.setForeground(new java.awt.Color(255, 255, 255));
        btnDOIS.setText("2");
        btnDOIS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDOIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDOISActionPerformed(evt);
            }
        });

        btnUM.setBackground(new java.awt.Color(63, 63, 63));
        btnUM.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnUM.setForeground(new java.awt.Color(255, 255, 255));
        btnUM.setText("1");
        btnUM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUMActionPerformed(evt);
            }
        });

        btnSEIS.setBackground(new java.awt.Color(63, 63, 63));
        btnSEIS.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnSEIS.setForeground(new java.awt.Color(255, 255, 255));
        btnSEIS.setText("6");
        btnSEIS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSEIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEISActionPerformed(evt);
            }
        });

        btnSUB.setBackground(new java.awt.Color(255, 102, 0));
        btnSUB.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnSUB.setForeground(new java.awt.Color(255, 255, 255));
        btnSUB.setText("-");
        btnSUB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSUBActionPerformed(evt);
            }
        });

        btnCINCO.setBackground(new java.awt.Color(63, 63, 63));
        btnCINCO.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnCINCO.setForeground(new java.awt.Color(255, 255, 255));
        btnCINCO.setText("5");
        btnCINCO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCINCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCINCOActionPerformed(evt);
            }
        });

        btnQUATRO.setBackground(new java.awt.Color(63, 63, 63));
        btnQUATRO.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnQUATRO.setForeground(new java.awt.Color(255, 255, 255));
        btnQUATRO.setText("4");
        btnQUATRO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQUATRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQUATROActionPerformed(evt);
            }
        });

        btnOITO.setBackground(new java.awt.Color(63, 63, 63));
        btnOITO.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnOITO.setForeground(new java.awt.Color(255, 255, 255));
        btnOITO.setText("8");
        btnOITO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOITO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOITOActionPerformed(evt);
            }
        });

        btnMUL.setBackground(new java.awt.Color(255, 102, 0));
        btnMUL.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnMUL.setForeground(new java.awt.Color(255, 255, 255));
        btnMUL.setText("×");
        btnMUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMULActionPerformed(evt);
            }
        });

        btnSETE.setBackground(new java.awt.Color(63, 63, 63));
        btnSETE.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnSETE.setForeground(new java.awt.Color(255, 255, 255));
        btnSETE.setText("7");
        btnSETE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSETEActionPerformed(evt);
            }
        });

        btnNOVE.setBackground(new java.awt.Color(63, 63, 63));
        btnNOVE.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnNOVE.setForeground(new java.awt.Color(255, 255, 255));
        btnNOVE.setText("9");
        btnNOVE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNOVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNOVEActionPerformed(evt);
            }
        });

        btnAPAGAR.setBackground(new java.awt.Color(45, 45, 45));
        btnAPAGAR.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnAPAGAR.setForeground(new java.awt.Color(255, 255, 255));
        btnAPAGAR.setText("<<");
        btnAPAGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAPAGARActionPerformed(evt);
            }
        });

        btnC.setBackground(new java.awt.Color(45, 45, 45));
        btnC.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnC.setForeground(new java.awt.Color(255, 255, 255));
        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnDIV.setBackground(new java.awt.Color(255, 102, 0));
        btnDIV.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnDIV.setForeground(new java.awt.Color(255, 255, 255));
        btnDIV.setText("÷");
        btnDIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDIVActionPerformed(evt);
            }
        });

        txfCAMPO.setEditable(false);
        txfCAMPO.setBackground(new java.awt.Color(0, 0, 0));
        txfCAMPO.setFont(new java.awt.Font("Segoe UI Light", 1, 65)); // NOI18N
        txfCAMPO.setForeground(new java.awt.Color(255, 255, 255));
        txfCAMPO.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfCAMPO.setText("0");

        btnEDIT.setBackground(new java.awt.Color(0, 0, 0));
        btnEDIT.setForeground(new java.awt.Color(255, 255, 255));
        btnEDIT.setText("Edit");
        btnEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEDITActionPerformed(evt);
            }
        });

        btnHISTORICO.setBackground(new java.awt.Color(0, 0, 0));
        btnHISTORICO.setForeground(new java.awt.Color(255, 255, 255));
        btnHISTORICO.setText("Histórico");
        btnHISTORICO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHISTORICOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfCAMPO, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAPAGAR, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnQUATRO, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCINCO, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSEIS, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSETE, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOITO, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNOVE, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSUB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMUL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnUM, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDOIS, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTRES, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSOM, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPONTO, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnZERO, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRESP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHISTORICO)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEDIT, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(btnHISTORICO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfCAMPO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAPAGAR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMUL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSUB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSETE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOITO, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNOVE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnQUATRO, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCINCO, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSEIS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTRES, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDOIS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUM, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSOM, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnZERO, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPONTO, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRESP, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnZEROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZEROActionPerformed
        if(txfCAMPO.getText().equals("0"))
        {
            txfCAMPO.setText("0");
        }
        else
        {
            txfCAMPO.setText(txfCAMPO.getText() + "0");
        }
    }//GEN-LAST:event_btnZEROActionPerformed

    private void btnAPAGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAPAGARActionPerformed
        if(txfCAMPO.getText().length() >= 2)
        {
            txfCAMPO.setText(txfCAMPO.getText().substring(0, txfCAMPO.getText().length()-1));
        }
        else
        {
            txfCAMPO.setText("0");
        }
    }//GEN-LAST:event_btnAPAGARActionPerformed

    private void btnUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUMActionPerformed
        if(txfCAMPO.getText().equals("0"))
        {
            txfCAMPO.setText("1");
        }
        else
        {
            if(multiplaConta == 1)
            {
                txfCAMPO.setText("1");
                multiplaConta = 0;
            }
            else
            {
                txfCAMPO.setText(txfCAMPO.getText() + "1");
            }
        }
    }//GEN-LAST:event_btnUMActionPerformed

    private void btnDOISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDOISActionPerformed
        if(txfCAMPO.getText().equals("0"))
        {
            txfCAMPO.setText("2");
        }
        else
        {
            if(multiplaConta == 1)
            {
                txfCAMPO.setText("2");
                multiplaConta = 0;
            }
            else
            {
                txfCAMPO.setText(txfCAMPO.getText() + "2");
            }
        }
    }//GEN-LAST:event_btnDOISActionPerformed

    private void btnTRESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTRESActionPerformed
        if(txfCAMPO.getText().equals("0"))
        {
            txfCAMPO.setText("3");
        }
        else
        {
            if(multiplaConta == 1)
            {
                txfCAMPO.setText("3");
                multiplaConta = 0;
            }
            else
            {
                txfCAMPO.setText(txfCAMPO.getText() + "3");
            }
        }
    }//GEN-LAST:event_btnTRESActionPerformed

    private void btnQUATROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQUATROActionPerformed
        if(txfCAMPO.getText().equals("0"))
        {
            txfCAMPO.setText("4");
        }
        else
        {
            if(multiplaConta == 1)
            {
                txfCAMPO.setText("4");
                multiplaConta = 0;
            }
            else
            {
                txfCAMPO.setText(txfCAMPO.getText() + "4");
            }
        }
    }//GEN-LAST:event_btnQUATROActionPerformed

    private void btnCINCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCINCOActionPerformed
        if(txfCAMPO.getText().equals("0"))
        {
            txfCAMPO.setText("5");
        }
        else
        {
            if(multiplaConta == 1)
            {
                txfCAMPO.setText("5");
                multiplaConta = 0;
            }
            else
            {
                txfCAMPO.setText(txfCAMPO.getText() + "5");
            }
        }
    }//GEN-LAST:event_btnCINCOActionPerformed

    private void btnSEISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEISActionPerformed
        if(txfCAMPO.getText().equals("0"))
        {
            txfCAMPO.setText("6");
        }
        else
        {
            if(multiplaConta == 1)
            {
                txfCAMPO.setText("6");
                multiplaConta = 0;
            }
            else
            {
                txfCAMPO.setText(txfCAMPO.getText() + "6");
            }
        }
    }//GEN-LAST:event_btnSEISActionPerformed

    private void btnSETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSETEActionPerformed
        if(txfCAMPO.getText().equals("0"))
        {
            txfCAMPO.setText("7");
        }
        else
        {
           if(multiplaConta == 1)
            {
                txfCAMPO.setText("7");
                multiplaConta = 0;
            }
            else
            {
                txfCAMPO.setText(txfCAMPO.getText() + "7");
            }
        }
    }//GEN-LAST:event_btnSETEActionPerformed

    private void btnOITOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOITOActionPerformed
        if(txfCAMPO.getText().equals("0"))
        {
            txfCAMPO.setText("8");
        }
        else
        {
            if(multiplaConta == 1)
            {
                txfCAMPO.setText("8");
                multiplaConta = 0;
            }
            else
            {
                txfCAMPO.setText(txfCAMPO.getText() + "8");
            }
        }
    }//GEN-LAST:event_btnOITOActionPerformed

    private void btnNOVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNOVEActionPerformed
        if(txfCAMPO.getText().equals("0"))
        {
            txfCAMPO.setText("9");
        }
        else
        {
            if(multiplaConta == 1)
            {
                txfCAMPO.setText("9");
                multiplaConta = 0;
            }
            else
            {
                txfCAMPO.setText(txfCAMPO.getText() + "9");
            }
        }
    }//GEN-LAST:event_btnNOVEActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        txfCAMPO.setText("0");
        num1 = 0;
        num2 = 0;
        resp = 0;
        op = null;
    }//GEN-LAST:event_btnCActionPerformed

    private void btnPONTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPONTOActionPerformed
       int pode = 0;
        for(int i = 0 ; i < txfCAMPO.getText().length() ; i++)
       {
           if( txfCAMPO.getText().substring(i, i+1).equals("."))
           {
               pode += 1;
           }
       }
        
        if(pode == 0)
        {
            txfCAMPO.setText(txfCAMPO.getText() + ".");
        }
        
    }//GEN-LAST:event_btnPONTOActionPerformed

    private void btnSOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSOMActionPerformed
        if(op == null)
        {
             num1 = Double.parseDouble(txfCAMPO.getText());
            op = "+";
            txfCAMPO.setText("0");
        }
        else
        {
                multiplaConta = 1;
                num2 = Double.parseDouble(txfCAMPO.getText());
               if(op.equals("+"))
               {
                   resp = num1 + num2;
               } 
               else
               {
                   if(op.equals("-"))
                   {
                       resp = num1 - num2;
                   }
                   else
                   {
                       if(op.equals("×"))
                       {
                           resp = num1 * num2;
                       }
                       else
                       {
                           if(op.equals("÷"))
                           {
                               resp = num1 / num2;
                           }
                       }
                   }
               }
               op = "+";
               String confere = "0";
               resposta = String.valueOf(resp);

               for(int i = resposta.length() ; !confere.equals(".") ; i--)
               {
                   if( resposta.substring(resposta.length()-1, resposta.length()).equals("0"))
                   {
                       resposta =  resposta.substring(0, resposta.length()-1);
                       confere = resposta.substring(resposta.length()-1, resposta.length());
                   }
                   else
                   {
                       confere = ".";
                   }
                   if( resposta.substring(resposta.length()-1, resposta.length()).equals("."))
                   {
                       resposta =  resposta.substring(0, resposta.length()-1);
                   }
               }
               num1 = resp;
               txfCAMPO.setText(resposta);
           }
           if(op.equals("÷") && num1 == 0 || num2 == 0)
           {
               txfCAMPO.setText("0");
           }
    }//GEN-LAST:event_btnSOMActionPerformed

    private void btnSUBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSUBActionPerformed
         if(op == null)
        {
             num1 = Double.parseDouble(txfCAMPO.getText());
             op = "-";
             txfCAMPO.setText("0");
        }
        else
        {
                multiplaConta = 1;
                num2 = Double.parseDouble(txfCAMPO.getText());
               if(op.equals("+"))
               {
                   resp = num1 + num2;
               } 
               else
               {
                   if(op.equals("-"))
                   {
                       resp = num1 - num2;
                   }
                   else
                   {
                       if(op.equals("×"))
                       {
                           resp = num1 * num2;
                       }
                       else
                       {
                           if(op.equals("÷"))
                           {
                               resp = num1 / num2;
                           }
                       }
                   }
               }
                 op = "-";
               String confere = "0";
               resposta = String.valueOf(resp);

               for(int i = resposta.length() ; !confere.equals(".") ; i--)
               {
                   if( resposta.substring(resposta.length()-1, resposta.length()).equals("0"))
                   {
                       resposta =  resposta.substring(0, resposta.length()-1);
                       confere = resposta.substring(resposta.length()-1, resposta.length());
                   }
                   else
                   {
                       confere = ".";
                   }
                   if( resposta.substring(resposta.length()-1, resposta.length()).equals("."))
                   {
                       resposta =  resposta.substring(0, resposta.length()-1);
                   }
               }
               num1 = resp;
               txfCAMPO.setText(resposta);
           }
           if(op.equals("÷") && num1 == 0 || num2 == 0)
           {
               txfCAMPO.setText("0");
           }
    }//GEN-LAST:event_btnSUBActionPerformed

    private void btnMULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMULActionPerformed
        if(op == null)
        {
             num1 = Double.parseDouble(txfCAMPO.getText());
             op = "×";
             txfCAMPO.setText("0");
        }
        else
        {
                multiplaConta = 1;
                num2 = Double.parseDouble(txfCAMPO.getText());
               if(op.equals("+"))
               {
                   resp = num1 + num2;
               } 
               else
               {
                   if(op.equals("-"))
                   {
                       resp = num1 - num2;
                   }
                   else
                   {
                       if(op.equals("×"))
                       {
                           resp = num1 * num2;
                       }
                       else
                       {
                           if(op.equals("÷"))
                           {
                               resp = num1 / num2;
                           }
                       }
                   }
               }
                 op = "×";
               String confere = "0";
               resposta = String.valueOf(resp);

               for(int i = resposta.length() ; !confere.equals(".") ; i--)
               {
                   if( resposta.substring(resposta.length()-1, resposta.length()).equals("0"))
                   {
                       resposta =  resposta.substring(0, resposta.length()-1);
                       confere = resposta.substring(resposta.length()-1, resposta.length());
                   }
                   else
                   {
                       confere = ".";
                   }
                   if( resposta.substring(resposta.length()-1, resposta.length()).equals("."))
                   {
                       resposta =  resposta.substring(0, resposta.length()-1);
                   }
               }
               num1 = resp;
               txfCAMPO.setText(resposta);
           }
           if(op.equals("÷") && num1 == 0 || num2 == 0)
           {
               txfCAMPO.setText("0");
           }
    }//GEN-LAST:event_btnMULActionPerformed

    private void btnDIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDIVActionPerformed
         if(op == null)
        {
             num1 = Double.parseDouble(txfCAMPO.getText());
         op = "÷";
             txfCAMPO.setText("0");
        }
        else
        {
                multiplaConta = 1;
                num2 = Double.parseDouble(txfCAMPO.getText());
               if(op.equals("+"))
               {
                   resp = num1 + num2;
               } 
               else
               {
                   if(op.equals("-"))
                   {
                       resp = num1 - num2;
                   }
                   else
                   {
                       if(op.equals("×"))
                       {
                           resp = num1 * num2;
                       }
                       else
                       {
                           if(op.equals("÷"))
                           {
                               resp = num1 / num2;
                           }
                       }
                   }
               }
                op = "÷";
               String confere = "0";
               resposta = String.valueOf(resp);

               for(int i = resposta.length() ; !confere.equals(".") ; i--)
               {
                   if( resposta.substring(resposta.length()-1, resposta.length()).equals("0"))
                   {
                       resposta =  resposta.substring(0, resposta.length()-1);
                       confere = resposta.substring(resposta.length()-1, resposta.length());
                   }
                   else
                   {
                       confere = ".";
                   }
                   if( resposta.substring(resposta.length()-1, resposta.length()).equals("."))
                   {
                       resposta =  resposta.substring(0, resposta.length()-1);
                   }
               }
               num1 = resp;
               txfCAMPO.setText(resposta);
           }
           if(op.equals("÷") && num1 == 0 || num2 == 0)
           {
               txfCAMPO.setText("0");
           }
    }//GEN-LAST:event_btnDIVActionPerformed

    private void btnRESPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRESPActionPerformed
        if(op != null)
        {
            num2 = Double.parseDouble(txfCAMPO.getText());
            if(op.equals("+"))
            {
                resp = num1 + num2;
            } 
            else
            {
                if(op.equals("-"))
                {
                    resp = num1 - num2;
                }
                else
                {
                    if(op.equals("×"))
                    {
                        resp = num1 * num2;
                    }
                    else
                    {
                        if(op.equals("÷"))
                        {
                            resp = num1 / num2;
                        }
                    }
                }
            }
            String confere = "0";
            resposta = String.valueOf(resp);
            
            for(int i = resposta.length() ; !confere.equals(".") ; i--)
            {
                if( resposta.substring(resposta.length()-1, resposta.length()).equals("0"))
                {
                    resposta =  resposta.substring(0, resposta.length()-1);
                    confere = resposta.substring(resposta.length()-1, resposta.length());
                }
                else
                {
                    confere = ".";
                }
                if( resposta.substring(resposta.length()-1, resposta.length()).equals("."))
                {
                    resposta =  resposta.substring(0, resposta.length()-1);
                }
            }
            registrarHistorico();
            num1 = resp;
            txfCAMPO.setText(resposta);
        }
        if(op.equals("÷") && num1 == 0 || num2 == 0)
        {
            txfCAMPO.setText("0");
        }
        op = "";
    }//GEN-LAST:event_btnRESPActionPerformed

    private void btnEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEDITActionPerformed
        frmEdit frmE = new frmEdit(null, true);
        frmE.setVisible(true);
        if(frmE.vetor[0] != null)
        {
            btnSOM.setBackground(frmE.vetor[0]);
            btnSUB.setBackground(frmE.vetor[0]);
            btnMUL.setBackground(frmE.vetor[0]);
            btnDIV.setBackground(frmE.vetor[0]);

            btnRESP.setBackground(frmE.vetor[1]);

            btnAPAGAR.setBackground(frmE.vetor[2]);
            btnC.setBackground(frmE.vetor[2]);
            btnPONTO.setBackground(frmE.vetor[2]);
        }
        
    }//GEN-LAST:event_btnEDITActionPerformed

    private void btnHISTORICOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHISTORICOActionPerformed
        frmHistorico frmH = new frmHistorico(null, true);
        frmH.setVisible(true);
        
        if(frmH.retornaResposta() != null)
        {
            txfCAMPO.setText(frmH.retornaResposta());
        }
    }//GEN-LAST:event_btnHISTORICOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmCalculadora dialog = new frmCalculadora(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAPAGAR;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCINCO;
    private javax.swing.JButton btnDIV;
    private javax.swing.JButton btnDOIS;
    private javax.swing.JButton btnEDIT;
    private javax.swing.JButton btnHISTORICO;
    private javax.swing.JButton btnMUL;
    private javax.swing.JButton btnNOVE;
    private javax.swing.JButton btnOITO;
    private javax.swing.JButton btnPONTO;
    private javax.swing.JButton btnQUATRO;
    private javax.swing.JButton btnRESP;
    private javax.swing.JButton btnSEIS;
    private javax.swing.JButton btnSETE;
    private javax.swing.JButton btnSOM;
    private javax.swing.JButton btnSUB;
    private javax.swing.JButton btnTRES;
    private javax.swing.JButton btnUM;
    private javax.swing.JButton btnZERO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txfCAMPO;
    // End of variables declaration//GEN-END:variables
}
