/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package apresentacao;

/**
 *
 * @author nickb
 */
public class frmHistorico extends javax.swing.JDialog {

    /**
     * Creates new form frmHistorico
     */
    public frmHistorico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    
    String retorno;
    String corte;
    int intervalo;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnV0 = new javax.swing.JButton();
        btnV1 = new javax.swing.JButton();
        btnV2 = new javax.swing.JButton();
        btnV3 = new javax.swing.JButton();
        btnV4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("HISTÓRICO");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        btnV0.setBackground(new java.awt.Color(0, 0, 0));
        btnV0.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        btnV0.setForeground(new java.awt.Color(255, 255, 255));
        btnV0.setText(frmCalculadora.vetor[0]);
        btnV0.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnV0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnV0ActionPerformed(evt);
            }
        });

        btnV1.setBackground(new java.awt.Color(0, 0, 0));
        btnV1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        btnV1.setForeground(new java.awt.Color(255, 255, 255));
        btnV1.setText(frmCalculadora.vetor[1]);
        btnV1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnV1ActionPerformed(evt);
            }
        });

        btnV2.setBackground(new java.awt.Color(0, 0, 0));
        btnV2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        btnV2.setForeground(new java.awt.Color(255, 255, 255));
        btnV2.setText(frmCalculadora.vetor[2]);
        btnV2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnV2ActionPerformed(evt);
            }
        });

        btnV3.setBackground(new java.awt.Color(0, 0, 0));
        btnV3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        btnV3.setForeground(new java.awt.Color(255, 255, 255));
        btnV3.setText(frmCalculadora.vetor[3]);
        btnV3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnV3ActionPerformed(evt);
            }
        });

        btnV4.setBackground(new java.awt.Color(0, 0, 0));
        btnV4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        btnV4.setForeground(new java.awt.Color(255, 255, 255));
        btnV4.setText(frmCalculadora.vetor[4]);
        btnV4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnV4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnV4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnV0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnV1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
            .addComponent(btnV2, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
            .addComponent(btnV3, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
            .addComponent(btnV4, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnV0, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnV1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnV2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnV3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnV4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnV0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnV0ActionPerformed
         retorno = btnV0.getText();
        dispose();
    }//GEN-LAST:event_btnV0ActionPerformed

    private void btnV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnV1ActionPerformed
         if(btnV1.getText().equals(""))
         {
             retorno  = "0";
         }
         else
         {
            retorno = btnV1.getText();
            dispose();
         }
    }//GEN-LAST:event_btnV1ActionPerformed

    private void btnV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnV2ActionPerformed
        retorno = btnV2.getText();
        dispose();
    }//GEN-LAST:event_btnV2ActionPerformed

    private void btnV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnV3ActionPerformed
         retorno = btnV3.getText();
        dispose();
    }//GEN-LAST:event_btnV3ActionPerformed

    private void btnV4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnV4ActionPerformed
        retorno = btnV4.getText();
        dispose();
    }//GEN-LAST:event_btnV4ActionPerformed

    public String retornaResposta()
    {
        for(int i = retorno.length() ; i > 0 ; i--)
        {
            if(retorno.substring(i-1, i).equals(" "))
            {
                intervalo = i;
                i = -1;
            }
        }
        corte = retorno.substring(intervalo);
        return corte;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmHistorico dialog = new frmHistorico(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnV0;
    private javax.swing.JButton btnV1;
    private javax.swing.JButton btnV2;
    private javax.swing.JButton btnV3;
    private javax.swing.JButton btnV4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
